# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.16

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/jn/Documents/Personal/NDEngine

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/jn/Documents/Personal/NDEngine

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/jn/Documents/Personal/NDEngine/CMakeFiles /home/jn/Documents/Personal/NDEngine/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/jn/Documents/Personal/NDEngine/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named run

# Build rule for target.
run: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 run
.PHONY : run

# fast build rule for target.
run/fast:
	$(MAKE) -f CMakeFiles/run.dir/build.make CMakeFiles/run.dir/build
.PHONY : run/fast

base/load.o: base/load.cpp.o

.PHONY : base/load.o

# target to build an object file
base/load.cpp.o:
	$(MAKE) -f CMakeFiles/run.dir/build.make CMakeFiles/run.dir/base/load.cpp.o
.PHONY : base/load.cpp.o

base/load.i: base/load.cpp.i

.PHONY : base/load.i

# target to preprocess a source file
base/load.cpp.i:
	$(MAKE) -f CMakeFiles/run.dir/build.make CMakeFiles/run.dir/base/load.cpp.i
.PHONY : base/load.cpp.i

base/load.s: base/load.cpp.s

.PHONY : base/load.s

# target to generate assembly for a file
base/load.cpp.s:
	$(MAKE) -f CMakeFiles/run.dir/build.make CMakeFiles/run.dir/base/load.cpp.s
.PHONY : base/load.cpp.s

base/ndconst.o: base/ndconst.cpp.o

.PHONY : base/ndconst.o

# target to build an object file
base/ndconst.cpp.o:
	$(MAKE) -f CMakeFiles/run.dir/build.make CMakeFiles/run.dir/base/ndconst.cpp.o
.PHONY : base/ndconst.cpp.o

base/ndconst.i: base/ndconst.cpp.i

.PHONY : base/ndconst.i

# target to preprocess a source file
base/ndconst.cpp.i:
	$(MAKE) -f CMakeFiles/run.dir/build.make CMakeFiles/run.dir/base/ndconst.cpp.i
.PHONY : base/ndconst.cpp.i

base/ndconst.s: base/ndconst.cpp.s

.PHONY : base/ndconst.s

# target to generate assembly for a file
base/ndconst.cpp.s:
	$(MAKE) -f CMakeFiles/run.dir/build.make CMakeFiles/run.dir/base/ndconst.cpp.s
.PHONY : base/ndconst.cpp.s

base/ndstruct.o: base/ndstruct.cpp.o

.PHONY : base/ndstruct.o

# target to build an object file
base/ndstruct.cpp.o:
	$(MAKE) -f CMakeFiles/run.dir/build.make CMakeFiles/run.dir/base/ndstruct.cpp.o
.PHONY : base/ndstruct.cpp.o

base/ndstruct.i: base/ndstruct.cpp.i

.PHONY : base/ndstruct.i

# target to preprocess a source file
base/ndstruct.cpp.i:
	$(MAKE) -f CMakeFiles/run.dir/build.make CMakeFiles/run.dir/base/ndstruct.cpp.i
.PHONY : base/ndstruct.cpp.i

base/ndstruct.s: base/ndstruct.cpp.s

.PHONY : base/ndstruct.s

# target to generate assembly for a file
base/ndstruct.cpp.s:
	$(MAKE) -f CMakeFiles/run.dir/build.make CMakeFiles/run.dir/base/ndstruct.cpp.s
.PHONY : base/ndstruct.cpp.s

run.o: run.cpp.o

.PHONY : run.o

# target to build an object file
run.cpp.o:
	$(MAKE) -f CMakeFiles/run.dir/build.make CMakeFiles/run.dir/run.cpp.o
.PHONY : run.cpp.o

run.i: run.cpp.i

.PHONY : run.i

# target to preprocess a source file
run.cpp.i:
	$(MAKE) -f CMakeFiles/run.dir/build.make CMakeFiles/run.dir/run.cpp.i
.PHONY : run.cpp.i

run.s: run.cpp.s

.PHONY : run.s

# target to generate assembly for a file
run.cpp.s:
	$(MAKE) -f CMakeFiles/run.dir/build.make CMakeFiles/run.dir/run.cpp.s
.PHONY : run.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... rebuild_cache"
	@echo "... edit_cache"
	@echo "... run"
	@echo "... base/load.o"
	@echo "... base/load.i"
	@echo "... base/load.s"
	@echo "... base/ndconst.o"
	@echo "... base/ndconst.i"
	@echo "... base/ndconst.s"
	@echo "... base/ndstruct.o"
	@echo "... base/ndstruct.i"
	@echo "... base/ndstruct.s"
	@echo "... run.o"
	@echo "... run.i"
	@echo "... run.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

